add_executable(gamecoe_tests
    main.cpp
    colorcoe_tests.cpp
    utils/paths_tests.cpp
    entity/entity_tests.cpp
    entity/sparse_set_tests.cpp
    entity/component_pool_tests.cpp
    entity/entities_tests.cpp
    entity/extraction_tests.cpp
    entity/command_buffer_tests.cpp
    component/transform_tests.cpp
    component/parent_child_tests.cpp
    component/scene_tag_tests.cpp
    component/shape_renderer_tests.cpp
    component/shape_collider_tests.cpp
)

target_link_libraries(gamecoe_tests
    PRIVATE
        gamecoe
        testcoe
)